### ISSUE TITLE
invalid dnsname when using Client::try_default()

### ISSUE THREAD

**Issue by andreclaudino** [kube-rs/kube-rs#596] opened 2021-07-21 21:41 UTC
Hi! I am following a simple example for listing pods, using `Client::try_default()` to instantiate the client, then listing pods in a namespace. The code is:

use k8s_openapi::api::core::v1::Pod;
use kube::{Client, api::{Api, ListParams}};
use simple_result::SimpleResult;

```
#[tokio::main]
async fn main() -> SimpleResult<()> {

    let namespace = "kubeflow";
    
    let client = Client::try_default().await?;

    let api = Api::<Pod>::namespaced(client.clone(), &namespace);

    let pods = api.list(&ListParams::default()).await?;

    for pod in pods {
        let new_pod = pod.clone();
        println!("{}, {:?}", new_pod.metadata.name.unwrap(), pod);
    }

    Ok(())
}

```

There is a kubernetes configuration file at `~/.kube/config`.

When reaching `api.list` the following error message is printed to terminal, and program crashes:

```
Error: HyperError(hyper::Error(Connect, Custom { kind: Other, error: "invalid dnsname" }))
```

My `Cargo.toml` follows the example:

```
[dependencies]
serde_json = "1.0.59"
serde = {version = "1.0", features = ["derive"]}

tokio = {version = "1.5.0", features = ["macros", "time", "rt-multi-thread"]}
futures = { version = "0.3", default-features = false }

kube = { version = "0.58.1", default-features = false, features = ["client", "rustls-tls"] }
kube-runtime = { version = "0.58.1" }
k8s-openapi = { version = "0.12.0", default-features = false, features = ["v1_20"] }
`` 

Any idea?

**Comment by clux** [comment] 2021-07-21 21:42
Just with a quick scan of the `rustls-tls` feature leads me to believe this is due to https://github.com/kube-rs/kube-rs/issues/587

**Comment by clux** [comment] 2021-07-21 21:44
Sorry, I meant https://github.com/kube-rs/kube-rs/issues/153

That said, the former issue might be a way to work around it.

**Comment by clux** [comment] 2021-07-21 21:47
Closing as a duplicate of #153 (same error message). But if you would like to test a potential fix, you could try the branch at https://github.com/kube-rs/kube-rs/pull/597 (or switch back to openssl, because this is a rustls limitation atm).

**Comment by clux** [comment] 2021-07-21 21:47
Closing as a duplicate of #153 (same error message). But if you would like to test a potential fix, you could try the branch at https://github.com/kube-rs/kube-rs/pull/597 (or switch back to openssl, because this is a rustls limitation atm).

**Closed by clux** 2021-07-21 21:47 UTC
Labels: client
