### ISSUE TITLE
Can't Create Namespace

### ISSUE THREAD

**Issue by that-soda-pop** [kube-rs/kube-rs#966] opened 2022-07-28 17:39 UTC
### Current and expected behavior

It seems I can create all objects except a namespace,
I get the following error:

>  ApiError: the server could not find the requested resource: NotFound (ErrorResponse { status: "Failure", message: "the server could not find the requested resource", reason: "NotFound", code: 404 }

running the serialized struct as json with kubectl apply works as expected.

### Additional context

```rust
    async fn create_namespace_if_missing(&self, namespace_name: &str) -> anyhow::Result<()> {
        let client = self.client.clone();

        let s: Api<Namespace> = Api::default_namespaced(client);
        if s.get(namespace_name).await.is_err() {
            debug!("missing namespace");
            let prj = Namespace {
                metadata: ObjectMeta {
                    name: Some(namespace_name.to_string()),
                    labels: bt_helper("name", namespace_name),
                    ..Default::default()
                },
                ..Default::default()
            };

            s.create(&Default::default(), &prj).await?;
        } else {
            debug!("namespace exists");
        }
        Ok(())
    }

fn bt_helper(k: &str, v: &str) -> Option<BTreeMap<String, String>> {
    let mut data = BTreeMap::new();
    data.insert(k.to_string(), v.to_string());
    Some(data)
}
```

### Environment

Client Version: v1.24.2
Kustomize Version: v4.5.4
Server Version: v1.24.2

### Configuration and features

kube = { version = "0.74.0", features = ["runtime", "derive"] }
k8s-openapi = { version = "0.15.0", features = ["v1_24"] }

**Comment by clux** [comment] 2022-07-28 20:21
This code is actually illegal in master because it's the same confusion source as was fixed in https://github.com/kube-rs/kube-rs/pull/956

The problem is that `Namespace` is not a Namespaced resource (as funny as that may sound); use `Api::all` instead.

**Closed** 2022-07-28 20:21 UTC
Labels: bug, invalid
